title: CoCoSys lab wiki
description: A wiki for the CoCoSys lab, more at https://anneurai.net/.
theme: just-the-docs
search_enabled: true


url: https://just-the-docs.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
